-- MySQL Script generated by MySQL Workbench
-- Tue May  4 17:58:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myDAta
-- -----------------------------------------------------
-- 
-- 

-- -----------------------------------------------------
-- Schema myDAta
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myDAta` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `myDAta` ;

-- -----------------------------------------------------
-- Table `myDAta`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myDAta`.`categories` ;

CREATE TABLE IF NOT EXISTS `myDAta`.`categories` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myDAta`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myDAta`.`products` ;

CREATE TABLE IF NOT EXISTS `myDAta`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(255) NOT NULL,
  `code` BIGINT NOT NULL,
  `nutrition_grade` CHAR(1) NOT NULL,
  `stores` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id`),
  INDEX `fk_products_categories1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `myDAta`.`categories` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
KEY_BLOCK_SIZE = 1;


-- -----------------------------------------------------
-- Table `myDAta`.`substitutes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myDAta`.`substitutes` ;

CREATE TABLE IF NOT EXISTS `myDAta`.`substitutes` (
  `product_id` INT NOT NULL,
  `substitute_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `substitute_id`),
  INDEX `fk_products_has_products_products2_idx` (`substitute_id` ASC) VISIBLE,
  INDEX `fk_products_has_products_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `myDAta`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_products_products2`
    FOREIGN KEY (`substitute_id`)
    REFERENCES `myDAta`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
